[workspace]
members = [
    "dns",
    "hash",
    "qrcode",
    "share",
    "system"
]
resolver = "3"

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]

[profile.release]
lto = true
strip = true
debug = false
panic = 'abort'
codegen-units = 1