[package]
name = "hash"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4"
md-5 = "0.10"
sha1 = "0.10"
sha2 = "0.10"
digest = "0.10"
crossbeam-channel = "0.5"

[profile.release]
lto = true
strip = true
debug = false
panic = 'abort'
codegen-units = 1