[package]
name = "system"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.37"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order"]