[package]
name = "hasher"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
md-5 = "0.10.6"
sha1 = "0.10.6"
sha2 = "0.10.8"
digest = "0.10.7"
crossbeam-channel = "0.5.15"

[profile.release]
lto = true
strip = true
debug = false
panic = 'abort'
codegen-units = 1